# Site Settings
title: BIG
tagline: roBot Intelligence Group
email: 
description: >
  Researching, developing, and testing autonomous robots at Carnegie Mellon University
baseurl:
url: "https://cmubig.github.io"
permalink: pretty

paginate: 5
paginate_path: "/research/page:num"

favicon: /assets/imgs/logos/big.png
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: null

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar
  - kramdown-parser-gfm

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressedme
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "BIG"
      layout: post
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  team:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

scholar:
  style: simple-ieee.csl
  bibliography_list_tag: "ul.no-bullet"
  bibliography_template: bibtemplate

exclude: [vendor]